apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: null
    ingress:
      - service: http://ingress-nginx-controller.ingress-nginx
