apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: null
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: cloudflared

